'use client';
import Title from '@/components/UI/title';
import Container from '@/components/container';
import Wrapper from '@/components/wrapper';
import { CopyIcon } from '@radix-ui/react-icons';
import {
  Blockquote,
  Card,
  Flex,
  IconButton,
  Separator,
  Strong,
} from '@radix-ui/themes';
import toast from 'react-hot-toast';

const books = [
  { book: 'Los Seis Pilares De La Autoestima' },
  { book: '12 reglas para vivir' },
  { book: '19th Century Actor Autobiographies' },
  { book: '20 pasos hacia adelante' },
  { book: 'A Brief History of the Internet' },
  { book: 'A Pair of Schoolgirls A Story of School Days' },
  { book: 'Adivina quién soy esta noche' },
  { book: 'Adivina quién soy' },
  { book: 'Adventures of Huckleberry Finn' },
  { book: 'Al oeste del eden' },
  { book: 'Alguien como tú' },
  { book: 'Alguien como yo' },
  { book: 'Alguien que no soy' },
  { book: 'Amar o depender' },
  { book: 'Amigos de otro mundo' },
  { book: 'Amigos sin más' },
  { book: 'Amigos y algo más' },
  { book: 'Anne of Green Gables' },
  { book: 'Antes de despertar' },
  { book: 'Antes de renunciar a tu empleo' },
  { book: 'Approaching Zero' },
  { book: 'Aprender a amar' },
  { book: 'Artania The Pharaohs Cry' },
  { book: 'Así es la puta vida' },
  { book: 'Atrévete a no gustar' },
  { book: 'Atrévete a retarme' },
  { book: 'Ayer no te vi en Babilonia' },
  { book: 'Ayesha the Return of She' },
  { book: 'Beyond Good and Evil' },
  { book: 'Buen entretenimiento' },
  { book: 'Call of the Goddess' },
  { book: 'Can You Forgive Her' },
  { book: 'Caperucita Roja A quién tienes miedo' },
  { book: 'Caperucita Roja' },
  { book: 'Capitalismo y pulsión de muerte' },
  { book: 'Cartas para Claudia' },
  { book: 'Cerebro y mindfulness' },
  { book: 'Ceros y unos' },
  { book: 'Chantaje emocional' },
  { book: 'Ciudad Fantasma' },
  { book: 'Código limpio' },
  { book: 'Cómo ganar amigos e influir sobre las personas 1' },
  { book: 'Cómo ganar amigos e influir sobre las personas' },
  { book: 'Como Iniciar un Negocio' },
  { book: 'Cómo mejorar su autoestima' },
  { book: 'Cómo suprimir las preocupaciones y disfrutar de la vida' },
  { book: 'Confianza en uno mis PDFDrivecom ' },
  { book: 'Conversaciones entre amigos' },
  { book: 'Cuando la criptografía falla' },
  { book: 'Cuentos de Antaño' },
  { book: 'Cuentos para pensar' },
  { book: 'Cuentos reunidos' },
  { book: 'Cuentos y relatos' },
  { book: 'Culpa mía' },
  { book: 'Culpa nuestra' },
  { book: 'Culpa tuya' },
  { book: 'Cupido La madre que te parió' },
  { book: 'Daredevils Hughes Investigations 0' },
  { book: 'Dark Desire A Billionaire Dark Romance' },
  { book: 'De qué putas madres estás hablando' },
  { book: 'De tanto amarte me olvidé de mí' },
  { book: 'Deberías hablar con alguien' },
  { book: 'Deja de chingarte' },
  { book: 'Déjate llevar' },
  { book: 'DESA KINCAID BOUNTY HUNTER' },
  { book: 'Deseo y placer La ciencia de las motivaciones' },
  { book: 'Deshojando margaritas' },
  { book: 'Designing Your Life' },
  { book: 'Despídete de la timidez' },
  { book: 'Despistes y franquezas' },
  { book: 'Dhammapada' },
  { book: 'Dime quien soy' },
  { book: 'Disculpa mi timidez' },
  { book: 'Diseñando apps para móviles' },
  { book: 'Dolor and Shadow' },
  { book: 'Domina el arte de hablar en público' },
  { book: 'Domina tu lenguaje corporal' },
  { book: 'Donde viven los monstruos' },
  { book: 'Donde vuelan las mariposas' },
  { book: 'Dracula' },
  { book: 'Dreams' },
  { book: 'El arte de conversar' },
  { book: 'Ejercicios de mindfulness para Dummies' },
  { book: 'El Adagio de la Locura' },
  { book: 'El arte de amar' },
  { book: 'El arte de conversar.pdf' },
  { book: 'El arte de no amargarse la vida' },
  { book: 'El camino de la autodependencia' },
  { book: 'El Camino de las Lágrimas' },
  { book: 'El camino del encuentro' },
  { book: 'El coraje de ser quien eres aunque no gustes' },
  { book: 'El cuadrante del flujo del dinero' },
  { book: 'El cuerpo humano' },
  { book: 'El ego es el enemigo' },
  { book: 'El egoísta' },
  { book: 'El extraño orden de las cosas' },
  { book: 'El fin de la ansiedad en niños y adolescentes' },
  { book: 'El fin del amor' },
  { book: 'El hombre en busca de sentido' },
  { book: 'El inversor inteligente' },
  { book: 'El juego del dinero' },
  { book: 'El libro de los abrazos' },
  { book: 'El libro del ego' },
  { book: 'El libro del té' },
  { book: 'El libro negro del programador' },
  { book: 'El maravilloso mago de Oz' },
  { book: 'El mejor de los pecados' },
  { book: 'El método' },
  { book: 'El patrón Bitcoin' },
  {
    book: 'El placer frustrado Las paradojas de la sexualidad moderna y su solución',
  },
  { book: 'El poder de los hábitos' },
  { book: 'El poder de los introvertidos' },
  { book: 'El poder del ahora' },
  { book: 'El poder del dinero' },
  { book: 'El poder del mago' },
  { book: 'El poder está dentro de ti' },
  { book: 'El porqué de las cosas' },
  { book: 'El porvenir de mi pasado' },
  { book: 'El Premio' },
  { book: 'El Principito' },
  { book: 'El quinto acuerdo' },
  { book: 'El secreto de la librera de París' },
  { book: 'El silencio entre tú y yo' },
  { book: 'El Sutil Arte de que te Importe un Carajo' },
  { book: 'El traidor' },
  { book: 'El trauma nuclear de la Conciencia' },
  { book: 'El último día de mi vida' },
  { book: 'Embrujo de espinas' },
  { book: 'En el corazón del bosque' },
  { book: 'En el enjambre' },
  { book: 'En el principio era el sentido' },
  { book: 'En el principio fue la linea de comandos' },
  { book: 'Enamorate de ti' },
  { book: 'Encyclopedia of Needlework' },
  { book: 'Entre líneas' },
  { book: "Escape the Sea Saved by Pirates 'book' 1" },
  { book: 'Evite ser utilizado' },
  { book: 'Fábulas morales' },
  { book: 'Filosofía del budismo Zen' },
  { book: 'Firmament Radialloy' },
  { book: 'Fluir Flow' },
  {
    book: 'Fuego la historia de la mujer que buscó justicia en una botella de gasolina',
  },
  { book: 'Fundamental B-SBWB OCR.pdf' },
  { book: 'Guardiana de fuego' },
  { book: 'Healing Her Heart' },
  { book: 'Hegel y el poder' },
  { book: 'Helarte de amar' },
  { book: 'Hiperculturalidad' },
  { book: 'Historias de fantasmas' },
  { book: 'Ichigo-ichie Haz de cada instante algo único' },
  { book: 'Ichigo-Ichie' },
  { book: 'Ikigai esencial' },
  { book: 'Incrementa tu IQ financiero' },
  { book: 'Indomable' },
  { book: 'Infocracia' },
  { book: 'Insólitas' },
  { book: 'Inventemos Bitcoin' },
  { book: 'Juega bien tus cartas' },
  { book: 'Jugaré contigo' },
  { book: 'La agonía del eros' },
  { book: 'La aventura de Malaspina' },
  { book: 'La biblia de la vagina' },
  { book: 'La buena fama' },
  { book: 'La burbuja terapéutica' },
  { book: 'La caza de hackers' },
  { book: 'La chica de la mafia' },
  { book: 'La ciencia de hacerse rico' },
  { book: 'La ciencia y la vida' },
  { book: 'La conducta de la vida' },
  { book: 'La dama de noche' },
  { book: 'La desaparición de los rituales' },
  { book: 'La edad de la punzada' },
  { book: 'La escuela de canto' },
  { book: 'La expulsión de lo distinto' },
  { book: 'La felicidad después del orden' },
  { book: 'La felicidad es un té contigo' },
  { book: 'La influencer' },
  { book: 'La inseguridad social' },
  { book: 'La librera de Madrid' },
  { book: 'La linterna de papel' },
  { book: 'La magia del orden' },
  { book: 'La metamorfosis' },
  { book: 'La presencia ignorada de Dios' },
  { book: 'La princesa de invierno' },
  { book: 'La psicología de la Gestalt' },
  { book: 'La psicología del dinero' },
  { book: 'La red oscura' },
  { book: 'La revolución de la glucosa' },
  { book: 'La sanación de las 5 heridas' },
  { book: 'La semana laboral de 4 horas' },
  { book: 'La sociedad del cansancio' },
  { book: 'La sombra del viento' },
  { book: 'La sorprendente verdad sobre qué nos motiva' },
  { book: 'La tienda de los sueños Un siglo de cuento fantástico mexicano' },
  { book: 'La vida secreta de los cuadros' },
  { book: 'La vida secreta del cerebro' },
  { book: 'La vida tranquila' },
  { book: 'Lady Felicity y el canalla' },
  { book: 'Las aventuras de Pinocho' },
  { book: 'Las cinco heridas que impiden ser uno mismo' },
  { book: 'Las horas perdidas' },
  { book: 'Las mujeres que aman demasiado' },
  { book: 'Libera tu magia' },
  { book: 'Little Women' },
  { book: 'Los bichos raros también se enamoran' },
  { book: 'Los buenos amigos' },
  { book: 'Los cinco lenguajes del amor' },
  { book: 'Los Cuatro Acuerdos' },
  { book: 'Los hombres son de Marte las mujeres son de Venus' },
  { book: 'Los límites del amor' },
  { book: 'Los ojos vendados' },
  { book: 'Los secretos de la cortesana' },
  { book: 'Los Secretos de la Mente Millonaria' },
  { book: 'Los viajes de Gulliver' },
  { book: 'Los viejos amigos' },
  { book: 'LOSS OF REASON' },
  { book: 'Mafalda Femenino singular' },
  { book: 'Maneras de amar Crecimiento personal Spanish Edition' },
  { book: 'Marilyn Monroe y las estrellas de Hollywood' },
  { book: 'Marked Valkyrie Academy Dragon Alliance' },
  { book: 'Más que amigos' },
  {
    book: 'Memoirs of Extraordinary Popular Delusions and the Madness of Crowds',
  },
  { book: 'Microsoft Word - John C Maxwell - El lado positivo del fracaso' },
  { book: 'Middlemarch' },
  { book: 'Mindfulness en la vida cotidiana' },
  { book: 'Mindfulness para Dummies' },
  { book: 'Muerte en el bosque' },
  { book: 'Muerte y alteridad' },
  { book: 'Mundos opuestos' },
  { book: 'Nacido de ninguna mujer' },
  { book: 'Night and Day' },
  { book: 'No-cosas' },
  { book: 'Oh Well You Know How Women Are' },
  { book: 'Otra Vuelta de Tuerca' },
  { book: 'Padre rico padre pobre 1' },
  { book: 'Padre rico padre pobre' },
  { book: 'Pareja Fecha de caducidad' },
  { book: 'Paycheck to Paycheck' },
  { book: 'Pensamiento monógamo terror poliamoroso' },
  { book: 'Peter Pan' },
  { book: 'Piense y hágase rico' },
  { book: 'Pizzería Vesubio' },
  {
    book: 'Por qué mentimos en especial a nosotros mismos La ciencia del engaño puesta al descubierto',
  },
  { book: 'Por si las voces vuelven' },
  { book: 'Primavera con una esquina rota' },
  { book: 'Privacidad es poder' },
  { book: 'Psicoanálisis y existencialismo' },
  { book: 'Psicología financiera' },
  { book: 'Psicopolítica' },
  { book: 'Psychotherapy' },
  { book: 'Putita golosa por un feminismo del goce' },
  { book: 'Querida yo tenemos que hablar conócete y sé feliz contigo' },
  { book: 'Quién de nosotros' },
  { book: 'Quién eres' },
  { book: 'Rafaela' },
  { book: 'Recuerdos del futuro' },
  { book: 'Reina del grito' },
  { book: 'Reinventarse' },
  { book: 'Romeo and Juliet' },
  { book: 'Russian Roulette Helena Hawthorn Series 1' },
  { book: 'Saca tiempo para ti' },
  { book: "Save the Sea Saved by Pirates 'book; 3" },
  { book: 'Sé amable contigo mismo' },
  { book: 'Sé quién eres' },
  { book: 'Series Starters' },
  { book: 'Sexo para inconformistas' },
  { book: 'Sexo y amor en tiempos de crisis' },
  { book: 'Shimriti' },
  { book: 'Si tú quieres te bajas la luna' },
  { book: 'Siddharta' },
  { book: 'Siempre con mis amigos' },
  { book: 'Sir Percy Hits Back' },
  { book: 'Smiles A Rose of the Cumberlands' },
  { book: 'Solo amigos' },
  { book: 'Temas de conversación' },
  { book: 'Tener o ser' },
  { book: 'The Adventures of Pinocchio' },
  { book: 'The After Hous' },
  { book: 'The Black Arrow' },
  { book: 'The Black Bag' },
  { book: 'The Demon Girl' },
  { book: 'The Faerie Queene' },
  { book: 'The Iliad' },
  { book: 'The Invisible Man A Grotesque Romance' },
  { book: 'The Making of a Matchmaker A Prequel' },
  { book: 'The Poppy War' },
  { book: 'The Power of Concentration' },
  { book: 'The Secret of Poppyridge Cove' },
  { book: 'The Story of Ivy' },
  { book: 'The Strange Case of Dr Jekyll and Mr Hyde' },
  { book: 'The Untroubled Mind' },
  { book: 'The War of the Worlds' },
  { book: 'The Yellow Wallpaper' },
  {
    book: 'Todo eso que no sé cómo explicarle a mi madre poliamor sexo y feminismo',
  },
  { book: 'Todos los amigos saben guardar secretos' },
  { book: 'Todos los secretos que yo no pude contar' },
  { book: 'Toma las riendas de tu vida' },
  { book: 'Tómate un respiro Mindfulness' },
  { book: 'Topología de la violencia' },
  { book: 'Tu corazón no está bien de la cabeza' },
  { book: 'Tú eres tu lugar seguro' },
  { book: 'Tu mirada en mi piel' },
  { book: 'Tus pasos en la escalera' },
  { book: 'Ulysses' },
  { book: 'Un matrimonio inconveniente' },
  { book: 'Un monstruo viene a verme' },
  { book: 'Una cura para el alma' },
  { book: 'Unknown' },
  { book: 'Usted puede sanar su vida' },
  { book: 'Viaje al Centro de la Tierra' },
  { book: 'Viejos amigos nuevos amigos' },
  { book: 'Vivir es un asunto urgente' },
  { book: 'When Totems Fall' },
  { book: 'Y si quedamos como amigos' },
  { book: 'Y sin embargo el amor' },
];

const copyMessage = (text: string) => {
  navigator.clipboard.writeText(text);
  toast.success('Copied');
};

const Metas = () => {
  return (
    <Container size='3'>
      <Wrapper>
        <Title text='Books List' />
        <Blockquote>{'buuuuu'}</Blockquote>
        <Separator size='4' />

        <Flex direction='column' gap='5'>
          {books.map(({ book }, i) => (
            <Card key={i}>
              <Strong>{i + 1} -</Strong> {book}{' '}
              <IconButton
                variant='ghost'
                onClick={() => {
                  copyMessage(book);
                }}
              >
                <CopyIcon />
              </IconButton>
            </Card>
          ))}
        </Flex>
      </Wrapper>
    </Container>
  );
};

export default Metas;
